version: '3.8'

services:
  # Main Next.js application
  windifi-fe:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: windifi-prod
    restart: unless-stopped

    # Resource limits for production stability
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.5'

    # Environment variables
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - PORT=3000
      - HOSTNAME=0.0.0.0

    # Health check configuration
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    # Logging configuration
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
        compress: 'true'

    # Security options
    security_opt:
      - no-new-privileges:true

    # Read-only root filesystem (except for Next.js cache)
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
      - /app/.next/cache:noexec,nosuid,size=100m

    # User mapping for security
    user: '1001:1001'

    # Network configuration
    networks:
      - windifi-network

  # Nginx reverse proxy for dev.windifi.com
  nginx:
    image: nginx:1.27-alpine
    container_name: windifi-nginx
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      windifi-fe:
        condition: service_healthy
    networks:
      - windifi-network
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'wget --no-verbose --tries=1 --spider http://localhost/api/health || exit 1',
        ]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  windifi-network:
    driver: bridge
    name: windifi-network

volumes:
  nginx_logs:
    driver: local
