version: '3.8'

services:
  windifi-fe:
    image: ghcr.io/${GITHUB_REPOSITORY:-windifi-fe}:${IMAGE_TAG:-latest}
    container_name: ${CONTAINER_NAME:-windifi-fe}
    restart: unless-stopped

    # Port mapping - production uses 80, development uses 3000
    ports:
      - '${APP_PORT:-3000}:3000'

    # Resource limits for production stability
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.5'

    # Environment variables
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - NEXT_TELEMETRY_DISABLED=1
      - PORT=3000
      - HOSTNAME=0.0.0.0

    # Health check configuration
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:3000/api/health || exit 1']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    # Logging configuration
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
        compress: 'true'

    # Security options
    security_opt:
      - no-new-privileges:true

    # Read-only root filesystem (except for Next.js cache)
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
      - /app/.next/cache:noexec,nosuid,size=100m

    # User mapping for security
    user: '1001:1001'

    # Network configuration
    networks:
      - windifi-network

  # Optional: Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: ${NGINX_CONTAINER_NAME:-windifi-nginx}
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      windifi-fe:
        condition: service_healthy
    networks:
      - windifi-network
    profiles:
      - production

  # Optional: Monitoring with basic metrics
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: windifi-cadvisor
    restart: unless-stopped
    ports:
      - '8080:8080'
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    privileged: true
    devices:
      - /dev/kmsg
    networks:
      - windifi-network
    profiles:
      - monitoring

networks:
  windifi-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  nginx_logs:
    driver: local
