version: '3.8'

services:
  windifi-fe:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: windifi-dev
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - PORT=3000
      - HOSTNAME=0.0.0.0
    volumes:
      # For development, mount source code for hot reload
      - ./src:/app/src:ro
      - ./public:/app/public:ro
      - ./package.json:/app/package.json:ro
    restart: unless-stopped
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    networks:
      - windifi-dev

networks:
  windifi-dev:
    driver: bridge
